name: ""
positions:
  - x: 0
    y: 0.9
  - x: 1
    y: 0.9
  - x: 2
    y: 0.6
  - x: 3
    y: 0.3
  - x: 4
    y: 0.6
  - x: 5
    y: 0.6
  - x: 10.5
    y: 0.6
  - x: 11.5
    y: 0.6
  - x: 12.5
    y: 0.3
  - x: 13.5
    y: 0.6
  - x: 14.5
    y: 0.9
  - x: 15.5
    y: 0.9
  - x: 0
    y: 1.9
  - x: 1
    y: 1.9
  - x: 2
    y: 1.6
  - x: 3
    y: 1.3
  - x: 4
    y: 1.6
  - x: 5
    y: 1.6
  - x: 10.5
    y: 1.6
  - x: 11.5
    y: 1.6
  - x: 12.5
    y: 1.3
  - x: 13.5
    y: 1.6
  - x: 14.5
    y: 1.9
  - x: 15.5
    y: 1.9
  - x: 0
    y: 2.9
  - x: 1
    y: 2.9
  - x: 2
    y: 2.6
  - x: 3
    y: 2.3
  - x: 4
    y: 2.6
  - x: 5
    y: 2.6
  - x: 10.5
    y: 2.6
  - x: 11.5
    y: 2.6
  - x: 12.5
    y: 2.3
  - x: 13.5
    y: 2.6
  - x: 14.5
    y: 2.9
  - x: 15.5
    y: 2.9
  - x: 2
    y: 3.6
  - x: 3.3
    y: 3.6
  - x: 4.6
    y: 3.6
  - x: 5.9
    y: 4.1
    rotation: 35
  - x: 6.8
    y: 5.2
    rotation: 70
  - x: 8.8
    y: 5.2
    rotation: -70
  - x: 9.6
    y: 4.1
    rotation: -35
  - x: 10.9
    y: 3.6
  - x: 12.2
    y: 3.6
  - x: 13.5
    y: 3.6
spacing: 2.6240286909743
keySize: 2.36102809324567
